# Build with something like: 
#   docker build -f ./Dockerfile.hosted --build-arg UPSTREAM_TAG=$(cat .keycloak_upstream_tag) --platform=linux/amd64 .
ARG UPSTREAM_TAG="latest"
FROM quay.io/keycloak/keycloak:${UPSTREAM_TAG}

COPY themes/ /opt/keycloak/themes/

# All env vars for hosted instances should be specified in 
# .env in the ol-infrastructure repo.

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
